--[[

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

]]--

sum = 0;
n1 = 1; n2 = 1; n3 = 1

repeat
  n3 = n1 + n2;  n1 = n2;  n2 = n3
  if n1 % 2 == 0 then sum = sum + n1 end
  print(n1, n2, n3, sum) --  <--this is really nice 
until n3 > 4 * 10^6

print (sum)

