/**
 * Created by Sneeuwpopsneeuw on 23-Feb-16.
 */
public class Problem002_EvenFibonacciNumbers {
    public static void main (String args[]) {
        int first = 1, second = 1, third = 1;
        int total = 0;

        while (third < 4_000_000) {
			third = first + second;
			first = second;
			second = third;

			if (second % 2 == 0)
				total += second;
		}

		System.out.println("ans = " + total);
    }
}


/*
   Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   Find the sum of all the even-valued terms in the sequence which do not
   exceed four million.
 */